### ISSUE TITLE
Why main thread only?

### ISSUE THREAD

**Issue by wcauchois** [Beepiz/BleGattCoroutines#39]
This is more of a question than an issue so I hope this is the right forum.

Why are all GattConnection operations restricted to the main UI thread? If you call them from any other thread, they throw an exception saying it's not supported "right now". Is there actually a restriction that BLE ops must be performed from the main thread, or is that restriction in place mostly to ensure that operations are issued from the _same thread_?

**Comment by LouisCAD** [comment]
Because I read that it is risky to use BLE with multiple threads. However, there's no proof of this risk, and maybe it was just to avoid race conditions, which is not a problem we should have as long as we're doing the operations sequentially. I'll consider dropping this check to allow using `Dispatchers.Default` or any other dispatcher/thread(s).
