### ISSUE TITLE
Migrate away from jcenter

### ISSUE THREAD

**Issue by joharei** [Beepiz/BleGattCoroutines#65]
You're probably aware of this, but [jcenter is being sunsetted](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), so this package should probably migrate to somewhere else soon.

**Comment by hannesvoss** [comment]
ping @LouisCAD

**Comment by gapfDev** [comment]
Any answer ? or are you moving to a different library guys? ,   @joharei , @hannesvoss

**Comment by joharei** [comment]
I moved to [Kable](https://github.com/JuulLabs/kable), which seems well maintained.

**Comment by gapfDev** [comment]
Thanks @joharei

**Comment by hannesvoss** [comment]
> I moved to [Kable](https://github.com/JuulLabs/kable), which seems well maintained.

Me too 👍🏼

**Comment by LouisCAD** [comment]
Hello, I'm sorry for having taken so much time to respond.

I made myself so busy with other projects that it's hard to find enough time to maintain this one, and I'm not super motivated when I know that [kable](https://github.com/JuulLabs/kable), which is working on multiple platforms, provides the same functionality.

Since jcenter keeps being accessible for existing versions, it's not really a priority to publish the same artifacts to Maven Central. However, if I end up finding the time to work on this project again, I will publish newer versions on Maven Central, for sure.

**Comment by LouisCAD** [comment]
Hello, last week, I finally published [a new version of the library](https://github.com/Beepiz/BleGattCoroutines/releases/tag/v0.5.0), (1004 days after the previous).

It's available on MavenCentral, and there's a smooth pipeline for future releases now.

**Comment by LouisCAD** [comment]
Thank you for your patience 🙏
